<?php

/**
 * hook_install()
 */
function d2f2_install() {
    $deployment_module_name = drush_prompt('Nom de votre module de deploiement ?', 'deployment');
    variable_set('deployment_module_path', dirname(__DIR__) . '/' . $deployment_module_name);
    print "Le nom de votre module est : " . $deployment_module_name;
}

function d2f2_uninstall() {
    variable_del('deployment_module_path');
}

?>
