<?php
/**
 * Librairie d'aide pour la configuration des FEATURES (uniquement) sur la production
 * ** NB **
 * Ces fonctions ne doivent pas être utilisées pour migrer du contenu
 */

require_once __DIR__ . '/d2f2.autoload.inc';


/*include_once('src/Filesystem/filesystem.php');
include_once('src/user.php');
include_once('src/node.php');
include_once('src/config.php');*/



/**
 * Implements hook_menu()
 * TODO : Générer automatiquement ce hook à l'installation du module
 */
function d2f2_menu() {

    $items['debug-deployment'] = array(
        'title' => 'Test déploiement',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('access content'),
        'page callback' => '_debug_deployment'
    );

    return $items;
}

function _debug_deployment() {


    //_write_app_config('TOTO2', 'new value 2');
    _write_app_config('TOTO3', 'new value 3');
   // _write_app_config('TOTO4', 'new value 4');
    //_write_app_config('TOTO5', 'new value 5');
    exit;

    print _hello_world();
    return 'Hello debug';
}

/**
 * Pour la mise à jour de tous les composants d'une feature
 * @param $modules
 */
function _features_revert_all_components($modules) {

    $reverts = array();
    foreach($modules as $module) {
        $feature = features_get_features($module);
        $components = array_keys($feature->info['features']);
        $reverts[$module] = $components;
    }

    features_revert($reverts);
}


/**
 * Pour rendre le script de déploiement un peu verbeux
 */
function _trace() {
    $traces = debug_backtrace();
    if(isset($traces[1]['function'])) {
        $function = $traces[1]['function'];
        echo 'Execution de la fonction ' . $function . '()';
    }
}

/**
 * Permet la création d'un menu
 * @param $menu_name
 * @param $title
 * @param $description
 */
function _create_menu($menu_name, $title, $description) {
    $menu_settings = array(
        'menu_name' => $menu_name,
        'title' => $title,
        'description' => $description
    );

    menu_save($menu_settings);
}