<?php
/**
 * Librairie d'aide pour la configuration des FEATURES (uniquement) sur la production
 * ** NB **
 * Ces fonctions ne doivent pas être utilisées pour migrer du contenu
 */

require_once __DIR__ . '/d2f2.autoload.inc';


/**
 * Implements hook_menu()
 */
function d2f2_menu() {

    $items['debug-deployment'] = array(
        'title' => 'Test déploiement',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('access content'),
        'page callback' => '_debug_deployment'
    );

    return $items;
}

function _debug_deployment() {

    //$file = _get_config_file(SITE_SETTINGS_FILE);
    //var_dump($file);exit;

    //var_dump(file_exists(PERMISSIONS_FILE));
    //var_dump(PERMISSIONS_FILE);
    _restore_permissions(PERMISSIONS_FILE, 'anonymous user');

    return 'Hello debug';
}

/**
 * Pour la mise à jour de tous les composants d'une feature
 * @param $modules
 */
function _features_revert_all_components($modules) {

    $reverts = array();
    foreach($modules as $module) {
        $feature = features_get_features($module);
        $components = array_keys($feature->info['features']);
        $reverts[$module] = $components;
    }

    features_revert($reverts);
}


/**
 * Pour rendre le script de déploiement un peu verbeux
 */
function _trace() {
    $traces = debug_backtrace();
    if(isset($traces[1]['function'])) {
        $function = $traces[1]['function'];
        echo 'Execution de la fonction ' . $function . '()';
    }
}

/**
 * Permet la création d'un menu
 * @param $menu_name
 * @param $title
 * @param $description
 */
function _create_menu($menu_name, $title, $description) {
    $menu_settings = array(
        'menu_name' => $menu_name,
        'title' => $title,
        'description' => $description
    );

    menu_save($menu_settings);
}