<?php
/**
 * Librairie d'aide pour la configuration des FEATURES (uniquement) sur la production
 * ** NB **
 * Ces fonctions ne doivent pas être utilisées pour migrer du contenu
 */

include_once('app/config.inc');

include_once('src/Filesystem/filesystem.php');
include_once('src/user.php');
include_once('src/node.php');
include_once('src/config.php');


/**
 * Implements hook_menu()
 * TODO : Générer automatiquement ce hook à l'installation du module
 */
function deployment_helper_menu() {

    $items['debug-deployment'] = array(
        'title' => 'Test déploiement',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('access content'),
        'page callback' => '_debug_deployment'
    );

    return $items;
}

function _debug_deployment() {

   /* $file = parse_ini_file(dirname(__DIR__) . '/deployment/config/account_settings.ini', TRUE);
    var_dump($file);*/

    //var_dump(variable_get('user_email_verification'));


    //variable_set('user_cancel_method', 1);
    //var_dump(variable_get('user_cancel_method'));

    write_app_config('TOTO2', 'value changed');

    return 'Hello debug';
}

/**
 * Pour la mise à jour de tous les composants d'une feature
 * @param $modules
 */
function _features_revert_all_components($modules) {

    $reverts = array();
    foreach($modules as $module) {
        $feature = features_get_features($module);
        $components = array_keys($feature->info['features']);
        $reverts[$module] = $components;
    }

    features_revert($reverts);
}


/**
 * Pour rendre le script de déploiement un peu verbeux
 */
function _trace() {
    $traces = debug_backtrace();
    if(isset($traces[1]['function'])) {
        $function = $traces[1]['function'];
        echo 'Execution de la fonction ' . $function . '()';
    }
}

/**
 * Permet la création d'un menu
 * @param $menu_name
 * @param $title
 * @param $description
 */
function _create_menu($menu_name, $title, $description) {
    $menu_settings = array(
        'menu_name' => $menu_name,
        'title' => $title,
        'description' => $description
    );

    menu_save($menu_settings);
}